import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata
export async function generateMetadata(): Promise<Metadata> {
  return {
    title: {
      template: "%s | Next Practice",
      default: "Next Practice",
    },
    description: "Generated by create next app",
    authors: [{ name: "Your Name" }],
    metadataBase: new URL("http://localhost:3000"),
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}>
        <header className="sticky top-0 z-50 w-full border-b bg-white/95 backdrop-blur">
          <nav className="container mx-auto px-4">
            <ul className="flex h-14 items-center justify-center space-x-8">
              <li>
                <Link href="/" className="text-sm font-medium hover:text-gray-600 transition-colors">
                  Home
                </Link>
              </li>
              <li>
                <Link href="/about" className="text-sm font-medium hover:text-gray-600 transition-colors">
                  About
                </Link>
              </li>
              <li>
                <Link href="/blog" className="text-sm font-medium hover:text-gray-600 transition-colors">
                  Blog
                </Link>
              </li>
              <li>
                <Link href="/post" className="text-sm font-medium hover:text-gray-600 transition-colors">
                  Posts
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        <main className="flex-1">
          {children}
        </main>
        <footer className="border-t py-6 md:py-0">
          <div className="container mx-auto flex h-14 items-center justify-center px-4">
            <p className="text-sm text-gray-500">© 2024 Your Company. All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
